apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpetemplate-test-3 App
name: rpetemplate-test-3
home: https://github.com/hmcts/rpetemplate-test-3
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.1
    repository: '@hmctspublic'

